import { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "he";

const EN = {
  // Nav
  discover: "Discover",
  search: "Search",
  wishlist: "Wishlist",
  inbox: "Inbox",
  me: "Me",

  // Auth
  logIn: "Log in",
  signUp: "Sign up",
  email: "Email",
  password: "Password",
  loading: "Loading…",
  createAccount: "Create account",
  or: "or",
  continueWithGoogle: "Continue with Google",
  continueWithApple: "Continue with Apple",
  checkEmail: "Check your email to confirm your account!",
  fashionLivesOn: "Fashion that lives on.",

  // Onboarding
  getStarted: "Get Started",
  welcomeTitle: "Welcome to",
  welcomeSubtitle: "Buy and sell secondhand clothing. Fashion that lives on.",
  whatsYourName: "What's your name?",
  howYouAppear: "This is how you'll appear to others.",
  fullName: "Full name",
  continue: "Continue",
  addABio: "Add a bio",
  bioHint: "Tell people a bit about your style. You can skip this.",
  bioLabel: "Bio",
  skip: "Skip",
  addAPhoto: "Add a photo",
  photoHint: "A profile photo helps buyers trust you. You can skip.",
  addPhoto: "Gallery",
  takePhoto: "Camera",
  looksGreat: "Looks great,",
  remove: "Remove",
  allowLocation: "Allow location?",
  locationHint: "We use your location to show you items nearby. You can change this anytime.",
  allowLocationAccess: "Allow Location Access",
  skipForNow: "Skip for now",
  settingUp: "Setting up…",

  // Discover
  drops: "Drops",
  swipeToFind: "Swipe to find your next fit",
  newest: "Newest",
  priceAsc: "Price ↑",
  priceDesc: "Price ↓",
  nearest: "Nearest",
  seenItAll: "You've seen it all!",
  noMoreItems: "No more items in your area. Try a different category or increase your search radius.",
  refreshFeed: "Refresh feed",
  increaseRadius: "Increase radius",
  ownListingError: "This is your own listing",
  cantStartChat: "Couldn't start chat",
  cantSaveItem: "Couldn't save item",
  undoLimitReached: "Undo limit reached for today. Come back tomorrow!",
  undoLastSwipe: "Undo last swipe",

  // Search
  searchPlaceholder: "Brand, item, keyword…",
  condition: "Condition",
  price: "Price",
  clearAllFilters: "Clear all filters",
  noResults: "No results",
  tryAdjusting: "Try adjusting your search or filters.",
  startTyping: "Start typing to search listings.",
  results: "results",
  result: "result",
  forQuery: "for",

  // Messages / Chat
  noMessagesYet: "No messages yet",
  startChatting: "Start chatting by tapping \"Message seller\" on any listing.",
  you: "You:",
  messagePlaceholder: "Message…",
  sayHello: "No messages yet. Say hello!",
  failedToSend: "Failed to send message",
  viewListing: "View →",
  itemSold: "This item has been sold",
  listingUnavailable: "This listing is no longer available",
  itemReserved: "This item is reserved",
  reportConversation: "Report conversation",
  writeReview: "Write review",
  editReview: "Edit review",
  editReviewTitle: "Edit Review",

  // Dialogs (shared)
  cancel: "Cancel",
  submit: "Submit",
  update: "Update",
  delete: "Delete",
  block: "Block",
  blocking: "Blocking…",
  unblock: "Unblock",
  save: "Save",
  saving: "Saving…",
  rating: "Rating",
  reviewLabel: "Review",
  optional: "(optional)",
  shareExperience: "Share your experience…",
  additionalDetails: "Additional details (optional)…",
  submitting: "Submitting…",
  submitReport: "Submit Report",
  selectReason: "Select a reason. Our team will review it.",
  reportConversationTitle: "Report Conversation",
  blockTitle: "Block",
  cantMessageAnymore: "You won't be able to message each other anymore. You can unblock from Settings → Blocked Users.",
  reportListingTitle: "Report Listing",
  reportReviewTitle: "Report Review",
  guidelinesViolation: "Let us know why this review violates our guidelines.",
  deleteListingTitle: "Delete listing?",
  deleteListingDesc: "This can't be undone. The listing will be permanently removed.",
  deleteReviewTitle: "Delete Review?",
  deleteReviewDesc: "This will permanently remove your review and update the seller's rating.",

  // Profile
  profile: "Profile",
  listings: "Listings",
  reviews: "reviews",
  noReviewsLabel: "No reviews",
  savedItems: "Saved",
  sellItem: "Sell Item",
  signOut: "Sign out",
  messages: "Messages",
  myReviews: "My Reviews",
  settings: "Settings",
  adminPanel: "Admin Panel",
  activeTab: "Active",
  soldTab: "Sold",
  noActiveListings: "No active listings yet.",
  nothingSold: "Nothing sold yet.",
  createListingBtn: "Create listing",
  followers: "Followers",
  following: "Following",
  addBio: "Add a bio…",
  shortBio: "A short bio…",

  // Settings
  currency: "Currency",
  language: "Language",
  location: "Location",
  updateLocation: "Update my location",
  locationSaved: "Location saved ✓",
  locationNotSet: "Not set — helps show nearby listings",
  searchRadius: "Search Radius",
  showWithin: "Show listings within",
  km: "km",
  notifications: "Notifications",
  pushNotifications: "Push Notifications",
  comingSoon: "Coming soon",
  privacySafety: "Privacy & Safety",
  blockedUsers: "Blocked Users",
  reportHistory: "Report History",
  history: "History",
  recentlySeen: "Recently Seen",
  support: "Support",
  helpFAQ: "Help & FAQ",
  signOutBtn: "Sign Out",
  appearance: "Appearance",
  lightMode: "Light",
  darkMode: "Dark",
  appVersion: "RE-WEAR v2.0 · Built with ♥",
  failedUpdateCurrency: "Failed to update currency",
  currencySetTo: "Currency set to",
  geolocationUnavailable: "Geolocation not available",
  locationUpdated: "Location updated!",
  cantGetLocation: "Couldn't get location",

  // Wishlist
  newCollection: "New",
  newCollectionTitle: "New Collection",
  nothingSavedYet: "Nothing saved yet",
  startSwiping: "Start swiping and save items you love — they'll appear here.",
  browseListings: "Browse listings",
  collectionEmpty: "This collection is empty.",
  create: "Create",
  rename: "Rename",
  shareCollection: "Share (make public)",
  makePrivate: "Make private",
  copiedLinkHint: "Copies share link to clipboard",
  inviteSomeone: "Invite someone",
  deleteCollection: "Delete collection",
  moveToCollection: "Move to collection",
  items: "items",
  item: "item",
  public: "Public",
  collectionRenamed: "Collection renamed",
  failedCreateCollection: "Failed to create collection",
  failedSendInvite: "Failed to send invite",
  inviteSent: "Invite sent!",
  inviteTo: "Invite to",
  searchByName: "Search by name…",
  noUsersFound: "No users found",
  done: "Done",
  collectionPublicMsg: "Collection is now public — link copied!",
  collectionPrivateMsg: "Collection is now private",
  removed: "Removed",
  invite: "Invite",

  // My Reviews
  myReviewsTitle: "My Reviews",
  noReviewsYet: "No reviews yet",
  reviewsWillAppear: "Reviews from buyers and sellers will appear here.",

  // Blocked Users
  blockedUsersTitle: "Blocked Users",
  noBlockedUsers: "No blocked users",
  usersYouBlock: "Users you block will appear here.",
  blockedAgo: "Blocked",

  // Report History
  reportHistoryTitle: "Report History",
  noReportsSubmitted: "No reports submitted",
  reportsWillAppear: "Reports you've submitted will appear here.",
  statusOpen: "Open",
  statusUnderReview: "Under Review",
  statusResolved: "Resolved",
  statusDismissed: "Dismissed",
  adminNote: "Admin note: ",
  submittedLabel: "Submitted",
  reportLabel: "report",

  // Recently Seen
  recentlySeenTitle: "Recently Seen",
  nothingSeenYet: "Nothing seen yet",
  viewOnDiscover: "Items you view on Discover will appear here.",
  soldBadge: "Sold",
  reservedBadge: "Reserved",

  // Create Listing
  editListing: "Edit listing",
  sellAnItem: "Sell an item",
  addPhotos: "Add photos",
  photosHint: "First photo is the cover. Drag to reorder. Up to 8 photos.",
  itemDetails: "Item details",
  setYourPrice: "Set your price",
  reviewListing: "Review your listing",
  titleField: "Title *",
  categoryField: "Category *",
  conditionField: "Condition *",
  brandField: "Brand",
  sizeField: "Size",
  colorsField: "Colors",
  descriptionField: "Description",
  priceField: "Price *",
  previewListing: "Preview listing",
  publishListing: "Publish listing",
  saveChanges: "Save changes",
  publishing: "Publishing…",
  hasSavedDraft: "You have a saved draft",
  discard: "Discard",
  resumeDraft: "Resume",
  skipPhotosForNow: "Skip photos for now",
  listingPublished: "Listing published!",
  listingUpdated: "Listing updated!",
  failedToDeleteListing: "Failed to delete listing",
  listingDeleted: "Listing deleted",
  genderField: "Gender",
  genderWomens: "Women's",
  genderMens: "Men's",
  genderUnisex: "Unisex",
  genderAll: "All",
  priceFlexibilityField: "Price flexibility",
  priceFixed: "Fixed",
  priceFixedDesc: "Price is final",
  priceFlexibleOption: "Flexible",
  priceFlexibleDesc: "Open to offers",
  priceFlexibleBadge: "Flexible",
  priceFlexiblePreview: "(Flexible)",
  coverLabel: "Cover",
  titlePlaceholder: "e.g. Vintage Levi's 501 Jeans",
  brandPlaceholder: "e.g. Nike, Zara",
  sizePlaceholder: "e.g. M, 32, EU42",
  descriptionPlaceholder: "Describe the item — style, fit, any flaws…",
  condNewWithTagsDesc: "Never worn, tags attached",
  condLikeNewDesc: "Worn once or twice, pristine",
  condGoodDesc: "Some light signs of wear",
  condFairDesc: "Visible wear, still great",
  validationMissingPhoto: "Please add at least one photo to continue",
  validationPleaseFillin: "Please fill in:",

  // Listing Detail
  listingNotFound: "Listing not found",
  goBack: "Go back",
  sizeLabel: "Size",
  awayLabel: "away",
  viewProfile: "View profile →",
  reportListing: "Report listing",
  reserve: "Reserve",
  markSold: "Mark Sold",
  unhide: "Unhide",
  hide: "Hide",
  relist: "Relist",
  edit: "Edit",
  messageSeller: "Message seller",
  opening: "Opening…",
  saved: "Saved",
  linkCopied: "Link copied!",

  // Seller Profile
  memberSince: "Member",
  forSale: "For Sale",
  soldCount: "Sold",
  unfollow: "Unfollow",
  follow: "Follow",
  writeAReview: "Write a review",
  editYourReview: "Edit your review",
  messageFirst: "Message this seller first to leave a review.",
  viewMyProfile: "View my profile",
  listingsTab: "Listings",
  reviewsTab: "Reviews",
  noListingsYet: "No listings yet.",
  noReviewsTabYet: "No reviews yet.",
  reportUser: "Report user",
  blockUser: "Block user",
  yourReview: "Your Review",
  reviewNotEditable: "This review is older than 7 days and can no longer be edited.",
  canDeleteIt: "You can delete it if you wish.",
  cantSeeListings: "You won't see each other's listings or be able to message each other. You can unblock from Settings → Blocked Users.",
  blockUserBtn: "Block User",
  userNotFound: "User not found",

  // Notifications
  notificationsTitle: "Notifications",
  noNotificationsYet: "No notifications yet",
  notificationsWillAppear: "Activity from followers, messages, and listings will appear here.",
  markAllRead: "Mark all read",
  collectionInviteTitle: "Collection Invite",
  invitedYouTo: "invited you to join",
  moreInvites: "more invites waiting",
  acceptInvite: "Accept",
  decline: "Decline",
  joinedCollection: "Joined",
  inviteDeclined: "Invite declined",
  onlyFollowersCanBeInvited: "You can only invite people you follow",

  // Search — people tab
  listingsTab2: "Listings",
  peopleTab: "People",
  noUsersFoundSearch: "No people found",
  trySearchingByName: "Try searching by name.",
  listingsCount: "listings",

  // Listing views
  viewsCount: "views",

  // Activity feed
  activityTitle: "Following",
  activityEmpty: "Nothing yet",
  activityEmptyHint: "Follow sellers to see their new listings here.",
  followingActivity: "Following",
};

const HE: typeof EN = {
  // Nav
  discover: "גלה",
  search: "חיפוש",
  wishlist: "מועדפים",
  inbox: "דואר נכנס",
  me: "אני",

  // Auth
  logIn: "התחבר",
  signUp: "הרשמה",
  email: "אימייל",
  password: "סיסמה",
  loading: "טוען…",
  createAccount: "צור חשבון",
  or: "או",
  continueWithGoogle: "המשך עם Google",
  continueWithApple: "המשך עם Apple",
  checkEmail: "בדוק את האימייל שלך לאישור החשבון!",
  fashionLivesOn: "אופנה שחיה הלאה.",

  // Onboarding
  getStarted: "בוא נתחיל",
  welcomeTitle: "ברוך הבא ל",
  welcomeSubtitle: "קנה ומכור בגדים יד שנייה. אופנה שחיה הלאה.",
  whatsYourName: "מה שמך?",
  howYouAppear: "כך תופיע לאחרים.",
  fullName: "שם מלא",
  continue: "המשך",
  addABio: "הוסף ביוגרפיה",
  bioHint: "ספר קצת על הסגנון שלך. ניתן לדלג.",
  bioLabel: "ביוגרפיה",
  skip: "דלג",
  addAPhoto: "הוסף תמונה",
  photoHint: "תמונת פרופיל עוזרת לקונים לסמוך עליך. ניתן לדלג.",
  addPhoto: "גלריה",
  takePhoto: "מצלמה",
  looksGreat: "נהדר,",
  remove: "הסר",
  allowLocation: "לאפשר גישה למיקום?",
  locationHint: "אנו משתמשים במיקומך כדי להציג פריטים בקרבת מקום. ניתן לשנות בכל עת.",
  allowLocationAccess: "אפשר גישה למיקום",
  skipForNow: "דלג כעת",
  settingUp: "מגדיר…",

  // Discover
  drops: "דרופס",
  swipeToFind: "החלק כדי למצוא את הלוק הבא שלך",
  newest: "חדש ביותר",
  priceAsc: "מחיר ↑",
  priceDesc: "מחיר ↓",
  nearest: "הקרוב ביותר",
  seenItAll: "ראית הכל!",
  noMoreItems: "אין עוד פריטים באזורך. נסה קטגוריה אחרת או הגדל את רדיוס החיפוש.",
  refreshFeed: "רענן פיד",
  increaseRadius: "הגדל רדיוס",
  ownListingError: "זה המוצר שלך",
  cantStartChat: "לא ניתן להתחיל שיחה",
  cantSaveItem: "לא ניתן לשמור פריט",
  undoLimitReached: "הגעת למגבלת הביטולים להיום. חזור מחר!",
  undoLastSwipe: "בטל החלקה אחרונה",

  // Search
  searchPlaceholder: "מותג, פריט, מילת מפתח…",
  condition: "מצב",
  price: "מחיר",
  clearAllFilters: "נקה את כל הסינונים",
  noResults: "אין תוצאות",
  tryAdjusting: "נסה לשנות את החיפוש או הסינונים.",
  startTyping: "התחל להקליד כדי לחפש מוצרים.",
  results: "תוצאות",
  result: "תוצאה",
  forQuery: "עבור",

  // Messages / Chat
  noMessagesYet: "אין הודעות עדיין",
  startChatting: "התחל לשוחח על ידי לחיצה על \"שלח הודעה למוכר\" בכל מוצר.",
  you: "אתה:",
  messagePlaceholder: "הודעה…",
  sayHello: "אין הודעות עדיין. תגיד שלום!",
  failedToSend: "שליחת ההודעה נכשלה",
  viewListing: "← צפה",
  itemSold: "פריט זה נמכר",
  listingUnavailable: "מוצר זה אינו זמין יותר",
  itemReserved: "פריט זה שמור",
  reportConversation: "דווח על שיחה",
  writeReview: "כתוב ביקורת",
  editReview: "ערוך ביקורת",
  editReviewTitle: "ערוך ביקורת",

  // Dialogs (shared)
  cancel: "ביטול",
  submit: "שלח",
  update: "עדכן",
  delete: "מחק",
  block: "חסום",
  blocking: "חוסם…",
  unblock: "בטל חסימה",
  save: "שמור",
  saving: "שומר…",
  rating: "דירוג",
  reviewLabel: "ביקורת",
  optional: "(אופציונלי)",
  shareExperience: "שתף את חוויתך…",
  additionalDetails: "פרטים נוספים (אופציונלי)…",
  submitting: "שולח…",
  submitReport: "שלח דיווח",
  selectReason: "בחר סיבה. הצוות שלנו יבדוק.",
  reportConversationTitle: "דווח על שיחה",
  blockTitle: "חסום",
  cantMessageAnymore: "לא תוכלו לשלוח הודעות זה לזה. ניתן לבטל חסימה מהגדרות ← משתמשים חסומים.",
  reportListingTitle: "דווח על מוצר",
  reportReviewTitle: "דווח על ביקורת",
  guidelinesViolation: "ספר לנו למה הביקורת מפרה את ההנחיות שלנו.",
  deleteListingTitle: "מחק מוצר?",
  deleteListingDesc: "לא ניתן לבטל פעולה זו. המוצר יוסר לצמיתות.",
  deleteReviewTitle: "מחק ביקורת?",
  deleteReviewDesc: "פעולה זו תסיר את הביקורת לצמיתות ותעדכן את דירוג המוכר.",

  // Profile
  profile: "פרופיל",
  listings: "מוצרים",
  reviews: "ביקורות",
  noReviewsLabel: "אין ביקורות",
  savedItems: "שמורים",
  sellItem: "מכור פריט",
  signOut: "התנתק",
  messages: "הודעות",
  myReviews: "הביקורות שלי",
  settings: "הגדרות",
  adminPanel: "פאנל ניהול",
  activeTab: "פעיל",
  soldTab: "נמכר",
  noActiveListings: "אין מוצרים פעילים עדיין.",
  nothingSold: "שום דבר לא נמכר עדיין.",
  createListingBtn: "צור מוצר",
  followers: "עוקבים",
  following: "עוקב אחרי",
  addBio: "הוסף ביוגרפיה…",
  shortBio: "ביוגרפיה קצרה…",

  // Settings
  currency: "מטבע",
  language: "שפה",
  location: "מיקום",
  updateLocation: "עדכן את המיקום שלי",
  locationSaved: "מיקום נשמר ✓",
  locationNotSet: "לא הוגדר — עוזר להציג מוצרים בקרבת מקום",
  searchRadius: "רדיוס חיפוש",
  showWithin: "הצג מוצרים בטווח של",
  km: "ק\"מ",
  notifications: "התראות",
  pushNotifications: "התראות דחיפה",
  comingSoon: "בקרוב",
  privacySafety: "פרטיות ובטיחות",
  blockedUsers: "משתמשים חסומים",
  reportHistory: "היסטוריית דיווחים",
  history: "היסטוריה",
  recentlySeen: "נצפה לאחרונה",
  support: "תמיכה",
  helpFAQ: "עזרה ושאלות נפוצות",
  signOutBtn: "התנתק",
  appearance: "מראה",
  lightMode: "בהיר",
  darkMode: "כהה",
  appVersion: "RE-WEAR v2.0 · נוצר עם ♥",
  failedUpdateCurrency: "עדכון המטבע נכשל",
  currencySetTo: "המטבע הוגדר ל",
  geolocationUnavailable: "שירותי מיקום אינם זמינים",
  locationUpdated: "המיקום עודכן!",
  cantGetLocation: "לא ניתן לקבל מיקום",

  // Wishlist
  newCollection: "חדש",
  newCollectionTitle: "אוסף חדש",
  nothingSavedYet: "לא שמרת כלום עדיין",
  startSwiping: "התחל להחליק ושמור פריטים שאהבת — הם יופיעו כאן.",
  browseListings: "עיין במוצרים",
  collectionEmpty: "האוסף הזה ריק.",
  create: "צור",
  rename: "שנה שם",
  shareCollection: "שתף (הפוך לציבורי)",
  makePrivate: "הפוך לפרטי",
  copiedLinkHint: "מעתיק קישור שיתוף ללוח",
  inviteSomeone: "הזמן מישהו",
  deleteCollection: "מחק אוסף",
  moveToCollection: "העבר לאוסף",
  items: "פריטים",
  item: "פריט",
  public: "ציבורי",
  collectionRenamed: "שם האוסף שונה",
  failedCreateCollection: "יצירת האוסף נכשלה",
  failedSendInvite: "שליחת ההזמנה נכשלה",
  inviteSent: "ההזמנה נשלחה!",
  inviteTo: "הזמן ל",
  searchByName: "חפש לפי שם…",
  noUsersFound: "לא נמצאו משתמשים",
  done: "סיום",
  collectionPublicMsg: "האוסף הפך לציבורי — הקישור הועתק!",
  collectionPrivateMsg: "האוסף הפך לפרטי",
  removed: "הוסר",
  invite: "הזמן",

  // My Reviews
  myReviewsTitle: "הביקורות שלי",
  noReviewsYet: "אין ביקורות עדיין",
  reviewsWillAppear: "ביקורות מקונים ומוכרים יופיעו כאן.",

  // Blocked Users
  blockedUsersTitle: "משתמשים חסומים",
  noBlockedUsers: "אין משתמשים חסומים",
  usersYouBlock: "משתמשים שתחסום יופיעו כאן.",
  blockedAgo: "חסום",

  // Report History
  reportHistoryTitle: "היסטוריית דיווחים",
  noReportsSubmitted: "לא הוגשו דיווחים",
  reportsWillAppear: "דיווחים שהגשת יופיעו כאן.",
  statusOpen: "פתוח",
  statusUnderReview: "בבדיקה",
  statusResolved: "נסגר",
  statusDismissed: "נדחה",
  adminNote: "הערת מנהל: ",
  submittedLabel: "הוגש",
  reportLabel: "דיווח",

  // Recently Seen
  recentlySeenTitle: "נצפה לאחרונה",
  nothingSeenYet: "לא צפית בשום דבר עדיין",
  viewOnDiscover: "פריטים שתצפה בהם ב'גלה' יופיעו כאן.",
  soldBadge: "נמכר",
  reservedBadge: "שמור",

  // Create Listing
  editListing: "ערוך מוצר",
  sellAnItem: "מכור פריט",
  addPhotos: "הוסף תמונות",
  photosHint: "התמונה הראשונה היא הכריכה. גרור לסדר מחדש. עד 8 תמונות.",
  itemDetails: "פרטי הפריט",
  setYourPrice: "קבע את המחיר",
  reviewListing: "בדוק את המוצר שלך",
  titleField: "כותרת *",
  categoryField: "קטגוריה *",
  conditionField: "מצב *",
  brandField: "מותג",
  sizeField: "מידה",
  colorsField: "צבעים",
  descriptionField: "תיאור",
  priceField: "מחיר *",
  previewListing: "תצוגה מקדימה",
  publishListing: "פרסם מוצר",
  saveChanges: "שמור שינויים",
  publishing: "מפרסם…",
  hasSavedDraft: "יש לך טיוטה שמורה",
  discard: "בטל",
  resumeDraft: "המשך",
  skipPhotosForNow: "דלג על תמונות לעכשיו",
  listingPublished: "המוצר פורסם!",
  listingUpdated: "המוצר עודכן!",
  failedToDeleteListing: "מחיקת המוצר נכשלה",
  listingDeleted: "המוצר נמחק",
  genderField: "מגדר",
  genderWomens: "נשים",
  genderMens: "גברים",
  genderUnisex: "יוניסקס",
  genderAll: "הכל",
  priceFlexibilityField: "גמישות מחיר",
  priceFixed: "קבוע",
  priceFixedDesc: "המחיר סופי",
  priceFlexibleOption: "גמיש",
  priceFlexibleDesc: "פתוח להצעות",
  priceFlexibleBadge: "גמיש",
  priceFlexiblePreview: "(גמיש)",
  coverLabel: "כריכה",
  titlePlaceholder: "לדוגמה: ג'ינס לוי'ס 501 וינטג'",
  brandPlaceholder: "לדוגמה: נייק, זארה",
  sizePlaceholder: "לדוגמה: M, 32, EU42",
  descriptionPlaceholder: "תאר את הפריט — סגנון, גזרה, כל פגם…",
  condNewWithTagsDesc: "לא נלבש מעולם, תגיות מחוברות",
  condLikeNewDesc: "נלבש פעם-פעמיים, במצב מושלם",
  condGoodDesc: "סימני שחיקה קלים",
  condFairDesc: "שחיקה גלויה, עדיין מצוין",
  validationMissingPhoto: "אנא הוסף לפחות תמונה אחת להמשך",
  validationPleaseFillin: "אנא מלא:",

  // Listing Detail
  listingNotFound: "המוצר לא נמצא",
  goBack: "חזור",
  sizeLabel: "מידה",
  awayLabel: "רחוק",
  viewProfile: "← צפה בפרופיל",
  reportListing: "דווח על מוצר",
  reserve: "סמן כשמור",
  markSold: "סמן כנמכר",
  unhide: "הסר הסתרה",
  hide: "הסתר",
  relist: "פרסם מחדש",
  edit: "ערוך",
  messageSeller: "שלח הודעה למוכר",
  opening: "פותח…",
  saved: "נשמר",
  linkCopied: "הקישור הועתק!",

  // Seller Profile
  memberSince: "חבר",
  forSale: "למכירה",
  soldCount: "נמכר",
  unfollow: "הפסק לעקוב",
  follow: "עקוב",
  writeAReview: "כתוב ביקורת",
  editYourReview: "ערוך את הביקורת שלך",
  messageFirst: "שלח הודעה למוכר זה תחילה כדי להשאיר ביקורת.",
  viewMyProfile: "צפה בפרופיל שלי",
  listingsTab: "מוצרים",
  reviewsTab: "ביקורות",
  noListingsYet: "אין מוצרים עדיין.",
  noReviewsTabYet: "אין ביקורות עדיין.",
  reportUser: "דווח על משתמש",
  blockUser: "חסום משתמש",
  yourReview: "הביקורת שלך",
  reviewNotEditable: "ביקורת זו ישנה מ-7 ימים ולא ניתן עוד לערוך אותה.",
  canDeleteIt: "ניתן למחוק אותה אם תרצה.",
  cantSeeListings: "לא תראו את מוצרי השניים ולא תוכלו לשלוח הודעות זה לזה. ניתן לבטל חסימה מהגדרות ← משתמשים חסומים.",
  blockUserBtn: "חסום משתמש",
  userNotFound: "המשתמש לא נמצא",

  // Notifications
  notificationsTitle: "התראות",
  noNotificationsYet: "אין התראות עדיין",
  notificationsWillAppear: "פעילות מעוקבים, הודעות ומוצרים תופיע כאן.",
  markAllRead: "סמן הכל כנקרא",
  collectionInviteTitle: "הזמנה לאוסף",
  invitedYouTo: "הזמין אותך להצטרף ל",
  moreInvites: "הזמנות נוספות ממתינות",
  acceptInvite: "קבל",
  decline: "דחה",
  joinedCollection: "הצטרפת ל",
  inviteDeclined: "ההזמנה נדחתה",
  onlyFollowersCanBeInvited: "ניתן להזמין רק משתמשים שאתה עוקב אחריהם",

  // Search — people tab
  listingsTab2: "מוצרים",
  peopleTab: "אנשים",
  noUsersFoundSearch: "לא נמצאו משתמשים",
  trySearchingByName: "נסה לחפש לפי שם.",
  listingsCount: "מוצרים",

  // Listing views
  viewsCount: "צפיות",

  // Activity feed
  activityTitle: "עוקבים",
  activityEmpty: "אין עדיין",
  activityEmptyHint: "עקוב אחרי מוכרים כדי לראות את המוצרים החדשים שלהם כאן.",
  followingActivity: "עוקבים",
};

const TRANSLATIONS = { en: EN, he: HE };

interface LanguageContextValue {
  lang: Language;
  setLang: (l: Language) => void;
  t: typeof EN;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    return (localStorage.getItem("rewear_lang") as Language) ?? "en";
  });

  function setLang(l: Language) {
    setLangState(l);
    localStorage.setItem("rewear_lang", l);
    document.documentElement.dir = l === "he" ? "rtl" : "ltr";
    document.documentElement.lang = l;
  }

  useEffect(() => {
    document.documentElement.dir = lang === "he" ? "rtl" : "ltr";
    document.documentElement.lang = lang;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t: TRANSLATIONS[lang], isRTL: lang === "he" }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used inside LanguageProvider");
  return ctx;
}
